### PR TITLE
feat: remove conflict between auth_plugin and plaintext_password

### LINKED ISSUE #116: creating user on aws rds mysql 8.0.35
Just looking for some advice, I am trying to create a user with the mysql user resource, but using the caching_sha2_password authentication method.

I cannot alter the default authentication method as aws has made that setting non accessible to users.

I have tried the following:

resource "mysql_user" "user_russell_morris_alt" {
  user     = "user_russell_morris_altpass"
  auth_plugin = caching_sha2_password 
  auth_string_hashed = password value from our vault (plain text)
  host     = "%"
}

resource "mysql_user" "user_russell_morris_alt" {
  user     = "user_russell_morris_altpass"
  auth_plugin = caching_sha2_password 
  auth_string_hashed = hashing the password using sha2(password, 256)
  host     = "%"
}

consistently facing Error: `failed executing SQL: Error 1827 (HY000): The password hash doesn't have the expected format.`

Am i using the wrong parameter combination or does it require the default authentication being altered at the RDS level?

Thank you for you patience

### PR DESCRIPTION
**Pull request by mcanevet**
fixes #116

### CODE REVIEW

**Comment by mcanevet** [comment]
It's a work in progress when trying to fix #116. @petoju could you please comment?

**Comment by petoju** [comment]
Could you please add at least basic tests?

Basically test creating user with custom auth_plugin and changing user's password using terraform test SDK (like other tests in the repo). And this with both caching_sha2_password and mysql_native_password.

**Comment by mcanevet** [comment]
@petoju done

**Comment by mcanevet** [comment]
@petoju done (I think)

**Comment by petoju** [comment]
Released in v3.0.65

**Pull request merged**
